# Generated by Django 2.2.17 on 2021-01-21 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('tagline', models.TextField(default='Tagline')),
                ('addresss', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('postal_address', models.CharField(max_length=128)),
                ('primary_contact', models.CharField(max_length=128)),
                ('secondary_contact', models.CharField(max_length=128, null=True)),
                ('email', models.CharField(max_length=128)),
                ('webiste', models.CharField(max_length=128)),
                ('summary_of_services', models.CharField(max_length=128)),
                ('logo', models.ImageField(upload_to='businessLogo/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('user_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('unit_of_category', models.TextField()),
                ('unit_of_value', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('user_compliance_deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_compliance_deduction', to=settings.AUTH_USER_MODEL)),
                ('user_organization_compliance_deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organization_compliance_deduction', to='organization.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceAllowance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('amount', models.IntegerField()),
                ('date_created', models.DateField(auto_now=True)),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('user_compliance_allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_compliance_allowance', to=settings.AUTH_USER_MODEL)),
                ('user_organization_compliance_allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organization_compliance_allowance', to='organization.Organization')),
            ],
        ),
    ]
