# Generated by Django 2.2.17 on 2021-01-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceallowance',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
