# Generated by Django 2.2.17 on 2021-01-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_complianceallowance_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceallowance',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='compliancededuction',
            name='unit_of_value',
            field=models.FloatField(),
        ),
    ]
