# Generated by Django 2.2.17 on 2021-01-21 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0004_organizationuploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('residence', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('dob', models.DateField()),
                ('home_town', models.CharField(max_length=128)),
                ('place_of_birth', models.CharField(max_length=128)),
                ('postal_address', models.CharField(max_length=128)),
                ('primary_contact', models.CharField(max_length=128)),
                ('secondary_contact', models.CharField(max_length=128, null=True)),
                ('marital_status', models.CharField(max_length=128)),
                ('social_security_number', models.CharField(max_length=128)),
                ('picture', models.ImageField(upload_to='EmployeeUpload/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('employee_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_organization', to='organization.Organization')),
                ('user_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeJobDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=128)),
                ('position_title', models.CharField(max_length=128)),
                ('employee_code', models.CharField(max_length=128, null=True)),
                ('start_date', models.DateField()),
                ('salary', models.FloatField()),
                ('bank', models.CharField(max_length=128)),
                ('branch', models.CharField(max_length=128)),
                ('acc_no', models.CharField(max_length=128)),
                ('comments', models.TextField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('employee_job_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_job_details', to='employee.Employee')),
                ('employee_job_details_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_job_details_organization', to='organization.Organization')),
                ('user_employee_job_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_employee_job_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
