# Generated by Django 2.2.17 on 2021-01-24 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0004_organizationuploads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0002_auto_20210121_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField()),
                ('date_created', models.DateField(auto_now=True)),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('employee_payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_payroll', to='employee.Employee')),
                ('payroll_paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_paid_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loanroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_loan', models.FloatField()),
                ('date_created', models.DateField(auto_now=True)),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(null=True)),
                ('terms', models.CharField(max_length=128, null=True)),
                ('paid_status', models.CharField(default='PENDING', max_length=128)),
                ('employee_loan_roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_loan_roll', to='employee.Employee')),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_by', to=settings.AUTH_USER_MODEL)),
                ('user_paid_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_paid_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Allowanceroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True)),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(null=True)),
                ('allowance_given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_given_by', to=settings.AUTH_USER_MODEL)),
                ('allowance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_category', to='organization.ComplianceAllowance')),
                ('employee_allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_allowance', to='employee.Employee')),
            ],
        ),
    ]
